version: '3'
services:
  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    env_file:
      - .env
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - "./data/mongo/data:/data/db"